services:
  app:
    image: ruby
    working_dir: /src
    volumes:
      - bundle:/usr/local/bundle
      - .:/src
    ports:
      - 3010:3000
    tty: true
    #command: bundle exec rails s -p 3000 -b 0.0.0.0

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    profiles:
      - mysql

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    profiles:
      - postgres

volumes:
  bundle:
    driver: local
